import { z } from 'zod';
import { INDIVIDUALLY_GRANTABLE_CAPABILITIES } from './userPermissions.js';

/**
 * Request contracts for account management.
 *
 * Every schema is `.strict()`, so a body may carry ONLY the fields named
 * here. That is what structurally prevents mass assignment: there is no
 * `role`, `capabilities`, `privileged`, `state`, `mustChangePassword`,
 * `userId`, or `email` field on the self-service endpoint for a client
 * to smuggle in, and supplying one is a 400 rather than a silently
 * ignored extra key.
 */

/**
 * A company CODE, as the database actually defines one.
 *
 * NOT a closed list. Organization Management creates companies at
 * runtime (migration 0035), so a three-value enum here would reject a
 * company the same application had just created - which is exactly the
 * defect this replaced. What is validated is the SHAPE the server
 * itself generates and the database enforces:
 *
 *   migration 0035  CHECK (code ~ '^[A-Z][A-Z0-9_]*$')
 *   organizationCodes.ts  bounded to 48 characters
 *
 * DELIBERATELY NOT TRIMMED OR UPPERCASED. Codes are generated by the
 * server and returned canonical, so a value arriving with whitespace or
 * in lower case is malformed input, not something to quietly repair -
 * silently rewriting it would mean the value stored differs from the
 * value sent. A malformed code is a 400.
 *
 * VALIDATING THE SHAPE IS NOT AUTHORIZATION. It only keeps obviously
 * impossible values out of a query; whether the company EXISTS, is
 * ACTIVE, and owns the requested Team + Position is decided against the
 * database by `resolveProvisioningDestination`, and re-checked by the
 * triggers inside the writing transaction.
 */
export const companyCodeSchema = z
  .string()
  .min(1)
  .max(48)
  .regex(/^[A-Z][A-Z0-9_]*$/, 'companyCode must be an uppercase organization code');

/**
 * Password shape accepted at the API boundary.
 *
 * Deliberately NOT an invented composition policy (no bespoke
 * character-class rules). Permit owns authentication now. This schema
 * enforces the same 12..256 bound used for an operator-set password
 * (`scripts/bootstrapCeo.ts`) and rejects values that are only whitespace.
 *
 * Not trimmed: leading/trailing whitespace is legitimate password
 * content, and silently rewriting a credential would mean the stored
 * password differs from what the human typed.
 */
export const passwordSchema = z
  .string()
  .min(12, 'password must be at least 12 characters')
  .max(256)
  .refine((value) => value.trim().length > 0, { message: 'password must not be blank' });

/**
 * Self-service password change. The target is ALWAYS the authenticated
 * caller (`req.auth.id`), so there is deliberately no target field of
 * any kind - `.strict()` rejects `userId`, `email`, `targetUserId`,
 * `displayName`, `role` and anything else outright.
 */
export const changePasswordBodySchema = z
  .object({
    newPassword: passwordSchema,
  })
  .strict();

/**
 * Site Manager employee provisioning. Only genuine provisioning input is
 * accepted: no privileged role, no capability list, no account state,
 * and no user id - the database assigns the new identity's UUID,
 * never the caller.
 */
export const createEmployeeBodySchema = z
  .object({
    email: z.string().trim().email().max(254),
    temporaryPassword: passwordSchema,
    displayName: z.string().trim().min(1).max(120),
    companyCode: companyCodeSchema,
    teamPositionId: z.string().uuid(),
  })
  .strict();

/**
 * CEO establishes an E-SET SITE_MANAGER privileged account.
 *
 * Deliberately carries NO company, team, or position field: a privileged
 * system account has none, and `.strict()` means a client that supplies
 * one is rejected rather than silently ignored. It also carries no role
 * field - the role this endpoint grants is fixed in the service, so no
 * request body can choose CEO.
 */
export const createSiteManagerBodySchema = z
  .object({
    email: z.string().trim().email().max(254),
    temporaryPassword: passwordSchema,
    displayName: z.string().trim().min(1).max(120),
  })
  .strict();

/** Grant/revoke SITE_MANAGER. The target is the validated route parameter; the body carries nothing at all. */
export const privilegedRoleChangeBodySchema = z.object({}).strict();

/**
 * Employee update. Every field is optional but the object may not be
 * empty, and `.strict()` means anything not named here - a role, a
 * capability list, an account state, an audit field - is rejected rather
 * than ignored. Company and Team + Position must move together, because
 * an assignment is only valid against the company that owns its team.
 */
export const updateEmployeeBodySchema = z
  .object({
    displayName: z.string().trim().min(1).max(120).optional(),
    companyCode: companyCodeSchema.optional(),
    teamPositionId: z.string().uuid().optional(),
  })
  .strict()
  .superRefine((body, ctx) => {
    if (body.displayName === undefined && body.companyCode === undefined && body.teamPositionId === undefined) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'at least one field must be supplied' });
    }
    if ((body.companyCode === undefined) !== (body.teamPositionId === undefined)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: 'companyCode and teamPositionId must be changed together',
        path: ['teamPositionId'],
      });
    }
  });

/**
 * Manager-initiated login-email transition. A new temporary password is
 * MANDATORY: changing the address without rotating the credential would
 * leave the old password valid on the new login.
 */
export const changeEmployeeEmailBodySchema = z
  .object({
    newEmail: z.string().trim().email().max(254),
    temporaryPassword: passwordSchema,
  })
  .strict();

/** Individual permission grant/revoke. The capability is a closed set, never an arbitrary name or array. */
export const employeePermissionBodySchema = z
  .object({
    capability: z.enum(INDIVIDUALLY_GRANTABLE_CAPABILITIES),
  })
  .strict();

/** Bounded pagination for the administrative audit history. */
export const employeeHistoryQuerySchema = z
  .object({
    page: z.coerce.number().int().min(1).max(10_000).default(1),
    pageSize: z.coerce.number().int().min(1).max(100).default(25),
  })
  .strict();

/**
 * Employee directory listing. Bounded pagination identical to the audit
 * history above, plus the three filters that map onto genuinely existing
 * columns (display name, account state, company code) - `.strict()`
 * rejects any other query key rather than ignoring it, so no filter can
 * be smuggled in that this schema does not name.
 */
export const employeeListQuerySchema = z
  .object({
    page: z.coerce.number().int().min(1).max(10_000).default(1),
    pageSize: z.coerce.number().int().min(1).max(100).default(25),
    search: z.string().trim().min(1).max(120).optional(),
    state: z.enum(['ACTIVE', 'DISABLED']).optional(),
    companyCode: companyCodeSchema.optional(),
  })
  .strict();

/** The privileged account a CEO-only action targets. */
export const privilegedUserIdParamsSchema = z.object({ id: z.string().uuid() }).strict();

/** Site Manager forgotten-password reset. The target comes from the authenticated, validated route parameter - never from the body. */
export const resetEmployeePasswordBodySchema = z
  .object({
    temporaryPassword: passwordSchema,
  })
  .strict();

export const employeeIdParamsSchema = z.object({
  id: z.string().uuid('id must be a UUID'),
});


/* ------------------------------------------------------------------ */
/* Organization Management (Phase 2)                                   */
/* ------------------------------------------------------------------ */

/**
 * An organization display name, as a person types it.
 *
 * Trimmed, bounded, and required to contain at least one letter or
 * digit - so a name made only of punctuation or whitespace is rejected
 * at the boundary rather than becoming an unreadable row. The database
 * independently enforces non-blankness and normalized uniqueness; this
 * is the friendly first refusal, not the authority.
 *
 * Deliberately NOT restricted to an alphabet: real companies and teams
 * legitimately use hyphens, ampersands, accents and digits.
 */
const organizationNameSchema = z
  .string()
  .trim()
  .min(2, 'name must be at least 2 characters')
  .max(120)
  .refine((value) => /[\p{L}\p{N}]/u.test(value), {
    message: 'name must contain at least one letter or number',
  });

/**
 * Create a company.
 *
 * `.strict()`, and it names exactly ONE field. That is what structurally
 * prevents a client from proposing the things that would be authority:
 * there is no `code` (the server generates it and the database freezes
 * it), no `id`, no `deactivatedAt`, no `teams`, and no capability,
 * privilege or flag of any kind. Supplying one is a 400, not a silently
 * ignored extra key.
 */
export const createCompanyBodySchema = z
  .object({
    name: organizationNameSchema,
  })
  .strict();

/**
 * Create a team inside a company.
 *
 * The company is the validated route parameter, never a body field - so
 * a caller cannot name one company in the path and another in the body.
 */
export const createTeamBodySchema = z
  .object({
    name: organizationNameSchema,
  })
  .strict();

/**
 * Associate a position with a team.
 *
 * Carries a NAME only. It carries no capability id, no capability name,
 * no `siteManagerAssignable`, and no privileged flag, because every one
 * of those is a trusted server concern: a runtime association always
 * receives exactly the applicant baseline, and assignability is set on
 * INSERT by the domain layer. `.strict()` makes an attempt to supply
 * any of them a 400 rather than something to be filtered out later.
 *
 * The position itself is a GLOBAL vocabulary row. The domain reuses an
 * existing row when the name already exists and mints one otherwise;
 * the client never chooses a position id.
 */
export const createTeamPositionBodySchema = z
  .object({
    positionName: organizationNameSchema,
  })
  .strict();

/** Deactivation carries nothing at all: the target is the route parameter. */
export const organizationDeactivateBodySchema = z.object({}).strict();

export const companyIdParamsSchema = z
  .object({ companyId: z.string().uuid('companyId must be a UUID') })
  .strict();

export const companyTeamParamsSchema = z
  .object({
    companyId: z.string().uuid('companyId must be a UUID'),
    teamId: z.string().uuid('teamId must be a UUID'),
  })
  .strict();

export const teamIdParamsSchema = z
  .object({ teamId: z.string().uuid('teamId must be a UUID') })
  .strict();

export const teamPositionIdParamsSchema = z
  .object({ teamPositionId: z.string().uuid('teamPositionId must be a UUID') })
  .strict();
